# Generated by Django 2.1.5 on 2019-01-23 15:57

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields
import rest_framework.compat


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=20)),
                ('is_int', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Modem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=10, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('updated_at',),
            },
        ),
        migrations.CreateModel(
            name='OperatorService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ussd', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modem_api.Operator')),
            ],
            options={
                'ordering': ('updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_stations', models.ManyToManyField(through='modem_api.OperatorService', to='modem_api.Operator')),
            ],
            options={
                'ordering': ('updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ServiceStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('pin', fernet_fields.fields.EncryptedCharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modem_api.Service')),
            ],
            options={
                'ordering': ('updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('free', 'FREE'), ('busy', 'BUSY'), ('offline', 'OFFLINE')], default='offline', max_length=100)),
                ('phone_number', models.CharField(max_length=14, validators=[rest_framework.compat.MinLengthValidator(9)])),
                ('imei', models.CharField(max_length=20, unique=True)),
                ('imsi', models.CharField(max_length=20)),
                ('port', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='modem_api.Modem')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modem_api.Operator')),
                ('services', models.ManyToManyField(through='modem_api.ServiceStation', to='modem_api.Service')),
            ],
            options={
                'ordering': ('updated_at',),
            },
        ),
        migrations.AddField(
            model_name='servicestation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_stations', to='modem_api.Station'),
        ),
        migrations.AddField(
            model_name='operatorservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_services', to='modem_api.Service'),
        ),
        migrations.AddField(
            model_name='operator',
            name='service_stations',
            field=models.ManyToManyField(through='modem_api.OperatorService', to='modem_api.Service'),
        ),
        migrations.AddField(
            model_name='answer',
            name='operator_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='modem_api.OperatorService'),
        ),
        migrations.AlterUniqueTogether(
            name='station',
            unique_together={('phone_number', 'modem')},
        ),
        migrations.AlterUniqueTogether(
            name='servicestation',
            unique_together={('service', 'station')},
        ),
        migrations.AlterUniqueTogether(
            name='operatorservice',
            unique_together={('service', 'operator')},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('order', 'operator_service')},
        ),
    ]
