# Generated by Django 2.1.5 on 2019-01-22 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rest_framework.compat


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modem_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=10, unique=True)),
                ('balance', models.IntegerField()),
                ('max_balance', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modem_api.Operator')),
            ],
            options={
                'ordering': ('updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('mno_id', models.CharField(max_length=100)),
                ('mno_respond', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modem_api.Station')),
            ],
            options={
                'ordering': ('updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('track_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('is_deposit', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('new', 'NEW'), ('pending', 'PENDING'), ('paid', 'PAID'), ('cancel', 'CANCEL')], default='new', max_length=100)),
                ('recipient', models.CharField(max_length=14, validators=[rest_framework.compat.MinLengthValidator(9)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momo_api.MobileWallet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('updated_at',),
            },
        ),
        migrations.AddField(
            model_name='proof',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momo_api.Transaction'),
        ),
    ]
